"""create app-owned tables

Revision ID: c12a80474cec
Revises:
Create Date: 2026-09-20 22:23:55.550353

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c12a80474cec"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journal_entry",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column(
            "sport",
            sa.Enum("RUNNING", "CYCLING", "SWIMMING", "STRENGTH", "OTHER", name="sport"),
            nullable=False,
        ),
        sa.Column("planned_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("actual_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rpe", sa.Integer(), nullable=True),
        sa.Column("mood", sa.Integer(), nullable=True),
        sa.Column("linked_activity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_journal_entry_day"), "journal_entry", ["day"], unique=False, schema="app"
    )
    op.create_table(
        "training_plan",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("race_date", sa.Date(), nullable=False),
        sa.Column("target_time_seconds", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("training_plan", schema="app")
    op.drop_index(op.f("ix_app_journal_entry_day"), table_name="journal_entry", schema="app")
    op.drop_table("journal_entry", schema="app")
    # ### end Alembic commands ###
